### ISSUE TITLE
Mailing Lists

### ISSUE THREAD

**Issue by texdraft** [g000001/g000001#3]
Hi. Is this your page? http://ml.cddddr.org/
If so, may I ask where you got the original archives? I want to try re-parsing them into a different format.

(I know where to get CL-SU-AI and lispnews but haven't been able to find the others.)

Thanks.

**Comment by g000001** [comment]
Hi,
Original data almost comes from www.saildart.org.
( for example http://www.saildart.org/CLCOMP.2[COM,LSP] )

These files are SAIL WAITS file format and some odd manner in point of unix manner view.

I had these odd files splitting by random work, and just processing by MHonArc.

goodluck!
